### ISSUE TITLE
Week 5 quiz:Base cases

### ISSUE THREAD

**Issue by nkartik01** [ChanchalKumarMaji/Introduction-to-Discrete-Mathematics-for-Computer-Science#1]
Answers are not visible.

**Comment by ChanchalKumarMaji** [comment]
> Answers are not visible.

Which one ? - please give the links.

**Comment by Shivalika20** [comment]
base case answer not visible

**Comment by Shivalika20** [comment]
in week 5 what are the answers for base case? They are hidden.
please tell.

**Comment by ChanchalKumarMaji** [comment]
> in week 5 what are the answers for base case? They are hidden.
> please tell.

Hi, please give the link ?

**Comment by RaviChan** [comment]
> > in week 5 what are the answers for base case? They are hidden.
> > please tell.
> 
> Hi, please give the link ?

Hi, I think it should be this link: 

https://github.com/ChanchalKumarMaji/Introduction-to-Discrete-Mathematics-for-Computer-Science-Specialization/blob/master/Introduction%20to%20Graph%20Theory/Week5/Quiz:%20Base%20Cases.png

**Comment by ChanchalKumarMaji** [comment]
> > > in week 5 what are the answers for base case? They are hidden.
> > > please tell.
> > 
> > 
> > Hi, please give the link ?
> 
> Hi, I think it should be this link:
> 
> https://github.com/ChanchalKumarMaji/Introduction-to-Discrete-Mathematics-for-Computer-Science-Specialization/blob/master/Introduction%20to%20Graph%20Theory/Week5/Quiz:%20Base%20Cases.png

Ok. Let me check. Thanks.

**Comment by RaviChan** [comment]
> in week 5 what are the answers for base case? They are hidden.
> please tell.

Hi @Shivalika20 ,
The answers are  [0] and [0,1]
